"""initial domain schema

Revision ID: b1519a146957
Revises: 
Create Date: 2026-07-13 11:49:05.215426
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b1519a146957'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('market_type', sa.Enum('CRYPTO_BINANCE', 'FOREX_OTC', 'NORMAL', 'SYNTHETIC', name='markettype'), nullable=False),
    sa.Column('is_otc', sa.Boolean(), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market_type', name='uq_asset_symbol_market')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_seq'), 'audit_events', ['seq'], unique=True)
    op.create_table('dataset_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_name'), 'dataset_versions', ['name'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis', sa.String(length=1024), nullable=False),
    sa.Column('primary_metric', sa.String(length=64), nullable=False),
    sa.Column('rejection_criterion', sa.String(length=512), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_name'), 'model_versions', ['name'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_versions_name'), 'strategy_versions', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'VIEWER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'ts_utc', 'source', name='uq_candle')
    )
    op.create_index(op.f('ix_candles_asset_id'), 'candles', ['asset_id'], unique=False)
    op.create_index(op.f('ix_candles_ts_utc'), 'candles', ['ts_utc'], unique=False)
    op.create_table('payout_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_seconds', sa.Integer(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_snapshots_asset_id'), 'payout_snapshots', ['asset_id'], unique=False)
    op.create_table('trading_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('PAPER', 'SHADOW', 'MANUAL', 'OFFICIAL_DISABLED', name='executionmode'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'HALTED', 'ENDED', name='sessionstatus'), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_sessions_user_id'), 'trading_sessions', ['user_id'], unique=False)
    op.create_table('balance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['trading_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_snapshots_session_id'), 'balance_snapshots', ['session_id'], unique=False)
    op.create_table('paper_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CALL', 'PUT', 'NO_TRADE', name='action'), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=False),
    sa.Column('entry_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('expiry_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Enum('CREATED', 'PENDING_CONFIRMATION', 'ACCEPTED', 'REJECTED', 'OPEN', 'WON', 'LOST', 'TIED', 'SOLD', 'CANCELLED', 'EXPIRED_WITHOUT_DATA', name='orderstate'), nullable=False),
    sa.Column('strategy_version_id', sa.Integer(), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['trading_sessions.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_orders_session_id'), 'paper_orders', ['session_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('p_up', sa.Float(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('feature_vector_hash', sa.String(length=64), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['trading_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_session_id'), 'predictions', ['session_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('result', sa.Enum('CREATED', 'PENDING_CONFIRMATION', 'ACCEPTED', 'REJECTED', 'OPEN', 'WON', 'LOST', 'TIED', 'SOLD', 'CANCELLED', 'EXPIRED_WITHOUT_DATA', name='orderstate'), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('settled_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['paper_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_order_id'), 'settlements', ['order_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CALL', 'PUT', 'NO_TRADE', name='action'), nullable=False),
    sa.Column('threshold_call', sa.Float(), nullable=False),
    sa.Column('threshold_put', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_prediction_id'), 'signals', ['prediction_id'], unique=False)
    op.create_table('external_manual_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('entry_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('payout', sa.Float(), nullable=True),
    sa.Column('result', sa.Enum('WON', 'LOST', 'TIED', 'SOLD', 'REJECTED', name='manualresult'), nullable=True),
    sa.Column('theoretical_result', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_manual_trades_signal_id'), 'external_manual_trades', ['signal_id'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('no_trade_reason', sa.Enum('PROBABILITY_TOO_LOW', 'PAYOUT_TOO_LOW', 'UNCERTAINTY_TOO_HIGH', 'LATENCY_TOO_HIGH', 'RISK_LIMIT', 'ACTIVE_POSITION_EXISTS', 'SESSION_HALTED', 'DATA_QUALITY', 'MODEL_UNAVAILABLE', 'MODEL_DEGRADED', 'MARKET_REGIME_UNSUPPORTED', 'KILL_SWITCH', 'COOLDOWN', name='notradereason'), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_decisions_signal_id'), 'risk_decisions', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_decisions_signal_id'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_external_manual_trades_signal_id'), table_name='external_manual_trades')
    op.drop_table('external_manual_trades')
    op.drop_index(op.f('ix_signals_prediction_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_settlements_order_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_predictions_session_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_paper_orders_session_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_balance_snapshots_session_id'), table_name='balance_snapshots')
    op.drop_table('balance_snapshots')
    op.drop_index(op.f('ix_trading_sessions_user_id'), table_name='trading_sessions')
    op.drop_table('trading_sessions')
    op.drop_index(op.f('ix_payout_snapshots_asset_id'), table_name='payout_snapshots')
    op.drop_table('payout_snapshots')
    op.drop_index(op.f('ix_candles_ts_utc'), table_name='candles')
    op.drop_index(op.f('ix_candles_asset_id'), table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_strategy_versions_name'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_model_versions_name'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_dataset_versions_name'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_audit_events_seq'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
